//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PeminjamanVideo
{
    using System;
    using System.Collections.Generic;
    
    public partial class MsPelanggan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MsPelanggan()
        {
            this.TrPinjams = new HashSet<TrPinjam>();
        }
    
        public string KdPelanggan { get; set; }
        public string NmPelanggan { get; set; }
        public string Alamat { get; set; }
        public string Telp { get; set; }
        public Nullable<decimal> Jaminan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrPinjam> TrPinjams { get; set; }
    }
}
