//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PeminjamanVideo
{
    using System;
    using System.Collections.Generic;
    
    public partial class MsVideo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MsVideo()
        {
            this.TrPinjams = new HashSet<TrPinjam>();
        }
    
        public string KdVideo { get; set; }
        public string NmVideo { get; set; }
        public string Produksi { get; set; }
        public Nullable<int> JenisVideo { get; set; }
        public int Stok { get; set; }
        public string Bahasa { get; set; }
    
        public virtual MsJenis MsJeni { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrPinjam> TrPinjams { get; set; }
        public bool IsDelete { get; internal set; }
    }
}
