//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PeminjamanVideo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrPinjam
    {
        public string KdTransaksi { get; set; }
        public System.DateTime TglPinjam { get; set; }
        public string KdPelanggan { get; set; }
        public string KdVideo { get; set; }
        public Nullable<int> LamaPinjam { get; set; }
        public Nullable<System.DateTime> TglKembali { get; set; }
        public Nullable<decimal> Denda { get; set; }
    
        public virtual MsPelanggan MsPelanggan { get; set; }
        public virtual MsVideo MsVideo { get; set; }
    }
}
